# Get a base image
FROM openmower
ENV DEBIAN_FRONTEND=noninteractive

# First stage: Pull the git and all submodules, other stages depend on it

COPY --link ./ /opt/open_mower_ros

WORKDIR /opt/open_mower_ros

RUN git submodule update --init --recursive

RUN rm /opt/open_mower_ros/src/CMakeLists.txt
RUN bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && cd /opt/open_mower_ros/src && catkin_init_workspace && cd .. && source /opt/prebuilt/slic3r/setup.bash && catkin_make -DCATKIN_BLACKLIST_PACKAGES=slic3r_wrapper"

RUN echo "export OM_SOFTWARE_VERSION=$(git describe --tags || git describe --always || echo "v0.0.0")" > version_info.env

COPY ./docker/openmower_entrypoint.sh /openmower_entrypoint.sh
RUN chmod +x /openmower_entrypoint.sh

ENTRYPOINT ["/openmower_entrypoint.sh"]
CMD ["bash", "-c", "service nginx start; service mosquitto start; roslaunch open_mower open_mower.launch --screen"]